# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d04d18c78795f8b12956e452601fa7a0fd53ea44614587a4cb2db516fef8cfa281553f5689caaaeecf4dad529a81217910987ba0676f63b3547d6c5a85c7205

test:
  secret_key_base: 37d96194d22093de5f55d3804630aab24946b8cdf5732b9562fe669b42c40b4414580fc53017679e8a7cd2a8ac257183ed772383adc54841b5f2e956ea931f30

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
